USE FINANCA;
 
SELECT A.IDMOV,B.NUMEROMOV AS 'RECIBO',D.NOME AS 'FORNECEDOR 2.2.14',B.CODUSUARIO,B.CODTMV,H.desc_STATUS AS 'STATUS',B.DATAEMISSAO,b.DATACANCELAMENTOMOV,B.CAMPOLIVRE1,B.CHAVEORIGEM,B.CHAVEORIGEM_NUMERICO,B.Historico AS 'HIST_MOV',C.DATACONTRATO,C.DATAINICIO,C.DATAFIM,C.CODIGOCONTRATO,C.NOME AS 'NOME_CONTRATO',E.NOME AS 'FORNECEDOR CONTRATO',B.VALORBRUTO,C.VALORCONTRATO,G.NOME AS 'GESTOR',F.NOME AS 'GERENTE',
CASE WHEN C.CODSTACNT LIKE '00001' THEN 'Aberto'
WHEN C.CODSTACNT LIKE '00002' THEN 'Encerrado' 
WHEN C.CODSTACNT LIKE '00003' THEN 'Pendente' 
WHEN C.CODSTACNT LIKE '00005' THEN 'Cancelado' 
WHEN C.CODSTACNT LIKE '00006' THEN 'Encerramento'
WHEN C.CODSTACNT LIKE '00008' THEN 'Encerrado Vigência' 
ELSE C.CODSTACNT END AS 'STATUS DO CONTRATO' FROM CONTRATOSB2B A
INNER JOIN HubDados.CorporeRM.TMOV B
ON A.IDMOV = B.IDMOV
INNER JOIN HubDados.CorporeRM.TCNT C
ON A.CODIGOCONTRATO COLLATE Latin1_General_CI_AI = C.CODIGOCONTRATO
INNER JOIN HubDados.CorporeRM.FCFO D
ON B.CODCFO = D.CODCFO
INNER JOIN HubDados.CorporeRM.FCFO E
ON C.CODCFO COLLATE Latin1_General_CI_AI = E.CODCFO
INNER JOIN HubDados.CorporeRM.TVEN F
ON C.CODVEN COLLATE Latin1_General_CI_AI  = F.CODVEN
INNER JOIN HubDados.CorporeRM.TVEN G
ON C.CODVEN2 COLLATE Latin1_General_CI_AI  = G.CODVEN
INNER JOIN dbo.descricao_STATUS H
ON B.STATUS = H.STATUS
ORDER BY DATACONTRATO,CODIGOCONTRATO DESC