USE HubDados
;
Declare @DATAHOJE DATETIME = GETDATE()
;
 
/* DROP TABLE IF EXISTS [FINANCA].dbo._fViagens
CREATE TABLE [FINANCA].dbo._fViagens
(
[IDVIAGEM]INT IDENTITY(1,1) PRIMARY KEY,
[NUMEROMOV] INT NOT NULL,
[STATUS.31] VARCHAR(10),
[STATUS.37] VARCHAR(10),
[STATUS.39] VARCHAR(10),
[STATUS.2.40] VARCHAR(10),
[STATUS.2.36] VARCHAR(10),
[STATUS.2.37] VARCHAR(10),
[STATUS.2.38] VARCHAR(10),
[DESCSTATUS] VARCHAR(255),
DATAATUALIZACAO DATETIME NOT NULL,
[DTEMISSAO.31] DATETIME,
[DTEMISSAO.37] DATETIME,
[DTEMISSAO.39] DATETIME,
[DTEMISSAO.2.40] DATETIME,
[DTEMISSAO.2.36] DATETIME,
[DTEMISSAO.2.37] DATETIME,
[DTEMISSAO.2.38] DATETIME,
)
 
;*/
 
WITH CRIAR_NUMEROMOV AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.1.31')
AND YEAR(DATACRIACAO) = '2024'
)
,CRIAR_NUMEROMOV_37 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.1.37')
AND YEAR(DATACRIACAO) = '2024'
)
,CRIAR_NUMEROMOV_39 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.1.39')
AND YEAR(DATACRIACAO) = '2024'
) 
,CRIAR_NUMEROMOV_1_2_37 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.2.37')
AND YEAR(DATACRIACAO) = '2024'
) 
,CRIAR_NUMEROMOV_1_2_40 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.2.40')
AND YEAR(DATACRIACAO) = '2024'
)
,CRIAR_NUMEROMOV_1_2_36 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.2.36')
AND YEAR(DATACRIACAO) = '2024'
) 
,CRIAR_NUMEROMOV_1_2_38 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.2.38')
AND YEAR(DATACRIACAO) = '2024'
) 
--SELECT DISTINCT STATUS FROM CRIAR_NUMEROMOV_1_2_38
INSERT INTO [FINANCA].dbo._fViagens_v2
SELECT A.NUMEROMOV
,A.STATUS AS 'STATUS.31'
,B.STATUS AS 'STATUS.37'
,C.STATUS AS 'STATUS.39'
,E.STATUS AS 'STATUS.2_40'
,F.STATUS AS 'STATUS.2_36'
,D.STATUS AS 'STATUS.2_37'
,G.STATUS AS 'STATUS.2_38'
,CASE WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' AND D.STATUS = 'Q' AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'Prestação negativa finalizada - valor a devolver - baixado'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' AND D.STATUS IS NULL AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'Prestação de contas finalizada - Sem devolução ou pagamento'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' AND D.STATUS IS NULL AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS = 'Q' THEN 'Pagamento de Diferença de Adiantamento - Pago'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' AND D.STATUS IS NULL AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS = 'F' THEN 'Pagamento de Diferença de Adiantamento - Pendente Pagamento'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' AND D.STATUS = 'F' AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'Devolução de Adiantamento de Viagem - Pendente Baixa'
WHEN A.STATUS = 'F' AND B.STATUS = 'A' AND C.STATUS IS NULL AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'SV com adiantamento  - viagem em curso/a ocorrer - pendente de PC'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'A' AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'PC positiva com adiantamento - pendente de conferência'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' AND D.STATUS = 'Q' AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'Devolução de Adiantamento de Viagem - Baixado'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'F' AND D.STATUS IS NULL AND E.STATUS = 'N' AND F.STATUS = 'Q'  AND G.STATUS IS NULL THEN 'Ressarcimento de Despesas de Viagem Sem Adiantamento - Pago'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'F' AND D.STATUS IS NULL AND E.STATUS = 'N' AND F.STATUS = 'F'  AND G.STATUS IS NULL THEN 'Ressarcimento de Despesas de Viagem sem adiantamento - Pendente Pagamento'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'F' AND D.STATUS IS NULL AND E.STATUS = 'N' AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'Prestação zerada - Finalizada'
WHEN A.STATUS = 'C' AND B.STATUS = 'C' AND C.STATUS IS NULL AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'SV Cancelada antes do adiantamento ocorrer'
WHEN A.STATUS = 'C' AND B.STATUS IS NULL AND C.STATUS IS NULL AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'Cancelado'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'A' AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'PC positiva sem adiantamento -  pendente de conferência'
WHEN A.STATUS = 'R' AND B.STATUS IS NULL AND C.STATUS IS NULL AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'SV - Não autorizado pelo superior'
WHEN A.STATUS = 'A' AND B.STATUS IS NULL AND C.STATUS IS NULL AND D.STATUS IS NULL AND E.STATUS IS NULL AND F.STATUS IS NULL AND G.STATUS IS NULL THEN 'SV zerada -  pendente de PC'
--WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'R'  THEN 'CASOS EXCEPCIONAIS UII'

ELSE A.STATUS END AS 'DESCSTATUS'
,@DATAHOJE as 'DATAATUALIZACAO'
,A.DATAEMISSAO AS 'EMISSAO.31'
,B.DATAEMISSAO AS 'EMISSAO.37'
,C.DATAEMISSAO AS 'EMISSAO.39'
,E.DATAEMISSAO AS 'EMISSAO.2_40'
,F.DATAEMISSAO AS 'EMISSAO.2_36'
,D.DATAEMISSAO AS 'EMISSAO.2_37'
,G.DATAEMISSAO AS 'EMISSAO.2_38'
FROM CRIAR_NUMEROMOV A
LEFT JOIN CRIAR_NUMEROMOV_37 B
ON A.NUMEROMOV = B.NUMEROMOV
LEFT JOIN CRIAR_NUMEROMOV_39 C
ON A.NUMEROMOV = C.NUMEROMOV
LEFT JOIN CRIAR_NUMEROMOV_1_2_37 D
ON A.NUMEROMOV = D.NUMEROMOV
LEFT JOIN CRIAR_NUMEROMOV_1_2_40 E
ON A.NUMEROMOV = E.NUMEROMOV
LEFT JOIN CRIAR_NUMEROMOV_1_2_36 F
ON A.NUMEROMOV = F.NUMEROMOV
LEFT JOIN CRIAR_NUMEROMOV_1_2_38 G
ON A.NUMEROMOV = G.NUMEROMOV
ORDER BY NUMEROMOV DESC