USE HUBDADOS;

DECLARE @DATAINICIO AS DATE = '2025-09-11'
DECLARE @DATAFIM AS DATE = '2025-10-14'
DECLARE @CODTMV AS VARCHAR(12) = '2.2.14'
;

WITH CC AS (
   SELECT
        NivelAcao.CODCCUSTO,
        NivelUnidade.CAMPOLIVRE AS ACAO,
        NivelProjeto.CAMPOLIVRE AS PROJETO,
        NivelAcao.CAMPOLIVRE AS UNIDADE
    FROM HUBDADOS.CorporeRM.GCCUSTO AS NivelAcao
    -- Corrigindo a lógica para buscar os níveis hierárquicos corretos
    LEFT JOIN HUBDADOS.CorporeRM.GCCUSTO AS NivelProjeto ON LEFT(NivelAcao.CODCCUSTO, 5) = NivelProjeto.CODCCUSTO
    LEFT JOIN HUBDADOS.CorporeRM.GCCUSTO AS NivelUnidade ON LEFT(NivelAcao.CODCCUSTO, 12) = NivelUnidade.CODCCUSTO
    WHERE 
     LEN(NivelAcao.CODCCUSTO) > 15 AND NivelAcao.ATIVO = 'T' AND NivelAcao.PERMITELANC = 'T'
	 )

, TOTAL AS (SELECT CODTMV, A.IDMOV, A.CODUSUARIO, A.CODLOC, A.CODCFO, D.IDPRD, D.NOMEFANTASIA, A.VALORBRUTOORIG, (C.PRECOUNITARIO * C.QUANTIDADE) AS 'VALOR', B.PERCENTUAL, ((C.PRECOUNITARIO * C.QUANTIDADE) / (B.PERCENTUAL / 100)) AS 'DIVIDIDO',  B.CODCCUSTO, E.UNIDADE, A.DATAEMISSAO FROM CorporeRM.TMOV A
LEFT JOIN CorporeRM.TITMMOVRATCCU B ON A.IDMOV = B.IDMOV 
LEFT JOIN CorporeRM.TITMMOV C ON B.IDMOV = C.IDMOV AND C.NSEQITMMOV = B.NSEQITMMOV
LEFT JOIN CorporeRM.TPRD D ON C.IDPRD = D.IDPRD
LEFT JOIN CC E ON B.CODCCUSTO = E.CODCCUSTO

)

SELECT * FROM TOTAL
WHERE (DATAEMISSAO BETWEEN @DATAINICIO AND @DATAFIM) AND CODTMV = @CODTMV