USE HUBDADOS;

DECLARE @DATAINICIO AS DATE = '2025-09-11'
DECLARE @DATAFIM AS DATE = '2025-10-14'
DECLARE @CODTMV AS VARCHAR(12) = '2.2.14'
;

WITH CC AS (
   SELECT
        NivelAcao.CODCCUSTO,
        NivelUnidade.CAMPOLIVRE AS ACAO,
        NivelProjeto.CAMPOLIVRE AS PROJETO,
        NivelAcao.CAMPOLIVRE AS UNIDADE
    FROM HUBDADOS.CorporeRM.GCCUSTO AS NivelAcao
    -- Corrigindo a lógica para buscar os níveis hierárquicos corretos
    LEFT JOIN HUBDADOS.CorporeRM.GCCUSTO AS NivelProjeto ON LEFT(NivelAcao.CODCCUSTO, 5) = NivelProjeto.CODCCUSTO
    LEFT JOIN HUBDADOS.CorporeRM.GCCUSTO AS NivelUnidade ON LEFT(NivelAcao.CODCCUSTO, 12) = NivelUnidade.CODCCUSTO
    WHERE 
     LEN(NivelAcao.CODCCUSTO) > 15 AND NivelAcao.ATIVO = 'T' AND NivelAcao.PERMITELANC = 'T'
	 )

, TOTAL AS (SELECT A.STATUS, H.desc_STATUS, CODTMV, A.IDMOV, A.CODUSUARIO, A.CODLOC, F.NOME 'DEPARTAMENTO', A.CODCFO, G.NOME AS 'FORNECEDOR', D.IDPRD, D.NOMEFANTASIA AS 'PRODUTO', A.VALORBRUTOORIG, (C.PRECOUNITARIO * C.QUANTIDADE) AS 'VALOR', B.PERCENTUAL, ((C.PRECOUNITARIO * C.QUANTIDADE) / (B.PERCENTUAL / 100)) AS 'DIVIDIDO',  B.CODCCUSTO, E.UNIDADE, A.DATAEMISSAO FROM CorporeRM.TMOV A
LEFT JOIN CorporeRM.TITMMOVRATCCU B ON A.IDMOV = B.IDMOV 
LEFT JOIN CorporeRM.TITMMOV C ON B.IDMOV = C.IDMOV AND C.NSEQITMMOV = B.NSEQITMMOV
LEFT JOIN CorporeRM.TPRD D ON C.IDPRD = D.IDPRD
LEFT JOIN CC E ON B.CODCCUSTO = E.CODCCUSTO
LEFT JOIN CorporeRM.GDEPTO F ON A.CODLOC = F.CODDEPARTAMENTO COLLATE SQL_Latin1_General_CP1_CI_AI AND A.CODFILIAL = F.CODFILIAL
LEFT JOIN CorporeRM.FCFO G ON A.CODCFO = G.CODCFO
LEFT JOIN FINANCA.DBO.descricao_STATUS H ON A.STATUS = H.STATUS
)

SELECT * FROM TOTAL
WHERE (DATAEMISSAO BETWEEN @DATAINICIO AND @DATAFIM) AND CODTMV = @CODTMV AND STATUS <> 'C'