USE HUBDADOS; --DETALHAMENTO DAS PARCELAS

DECLARE @DATAINICIO AS DATE = '2025-09-11'
DECLARE @DATAFIM AS DATE = '2025-10-15'
DECLARE @CODTMV AS VARCHAR(12) = '2.2.14'
;

WITH LANCAMENTOS AS (
SELECT A.IDMOV, A.IDLAN, B.DESCFORMAPAGTO, A.DESCSTATUSLCTO, A.CODCFO, A.VALORBAIXADO, A.DATAVENCIMENTO, A.DATABAIXA FROM CorporeRM.FLAN A
LEFT JOIN CorporeRM.TFORMAPAGTO B ON A.IDFORMAPAGTO = B.IDFORMAPAGTO
)

, TOTAL AS (SELECT A.STATUS, H.desc_STATUS, CODTMV, A.IDMOV, I.IDLAN, I.DESCFORMAPAGTO, I.DESCSTATUSLCTO, A.CODUSUARIO, I.VALORBAIXADO, A.VALORBRUTOORIG,
A.CODLOC, F.NOME 'DEPARTAMENTO', A.CODCFO, G.NOME AS 'FORNECEDOR', A.DATAEMISSAO, I.DATABAIXA, I.DATAVENCIMENTO
FROM CorporeRM.TMOV A
LEFT JOIN CorporeRM.GDEPTO F ON A.CODLOC = F.CODDEPARTAMENTO COLLATE SQL_Latin1_General_CP1_CI_AI AND A.CODFILIAL = F.CODFILIAL
LEFT JOIN CorporeRM.FCFO G ON A.CODCFO = G.CODCFO
LEFT JOIN FINANCA.DBO.descricao_STATUS H ON A.STATUS = H.STATUS
LEFT JOIN LANCAMENTOS I ON A.IDMOV = I.IDMOV
)

SELECT * FROM TOTAL
WHERE (DATAEMISSAO BETWEEN @DATAINICIO AND @DATAFIM) AND CODTMV = @CODTMV AND STATUS <> 'C'
ORDER BY DATAEMISSAO DESC