USE HUBDADOS;

WITH TMOV AS (
    SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO, CHAVEORIGEM_NUMERICO, NUMEROMOV, STATUS, CODLOC, CODFILIAL
    FROM CorporeRM.TMOV WITH (NOLOCK)
    WHERE YEAR(DATAEMISSAO) = '2025'
    AND CODTMV IN ('2.1.19') AND STATUS = 'A'
),
ITMMOV AS (
    SELECT IDMOV, IDPRD, NSEQITMMOV
    FROM CorporeRM.TITMMOV WITH (NOLOCK)
),
TPRD AS (
    SELECT IDPRD, NOMEFANTASIA
    FROM CorporeRM.TPRD WITH (NOLOCK)
),
RATEIO AS (
    SELECT * FROM CorporeRM.TITMMOVRATCCU WHERE CODCCUSTO LIKE '00059%'
),
FORNCEDOR AS (
    SELECT CODCFO, NOME, NOMEFANTASIA, CGCCFO FROM CorporeRM.FCFO
),
CC AS (
    SELECT
        A.CODCCUSTO,
        B.NOME AS UNIDADE,
        C.NOME AS PROJETO,
        D.NOME AS ACAO
    FROM CorporeRM.GCCUSTO A
    INNER JOIN HUBDADOS.CorporeRM.GCCUSTO B   ON A.CODCCUSTO = B.CODCCUSTO
    INNER JOIN HUBDADOS.CorporeRM.GCCUSTO C   ON LEFT(A.CODCCUSTO, 5) = C.CODCCUSTO
    INNER JOIN HUBDADOS.CorporeRM.GCCUSTO D   ON LEFT(A.CODCCUSTO, 12) = D.CODCCUSTO
    WHERE
        LEN(A.CODCCUSTO) > 15
),
UNIAO AS (
    SELECT 
        A.IDMOV,
        A.STATUS,
        A.DATAEMISSAO,
        C.IDMOVRATCCU,
        A.CHAVEORIGEM_NUMERICO,
        E.CGCCFO AS CNPJ,
        A.NUMEROMOV,
        C.CODCCUSTO AS RATEIO,
        C.VALOR,
        D.NOMEFANTASIA AS PRODUTO,
        E.CODCFO,
        A.CODLOC,
        G.NOME AS ESTOQUE,
        F.CODCCUSTO,
        F.UNIDADE,
        F.PROJETO,
        F.ACAO,
        E.NOME AS CLIENTE,
        CASE 
            WHEN F.UNIDADE LIKE 'SP - Relacionamento com Cliente' 
            THEN G.NOME COLLATE DATABASE_DEFAULT 
            ELSE F.UNIDADE 
        END AS 'CONTABILIZA_PARA'
    FROM TMOV A
    LEFT JOIN ITMMOV B ON A.IDMOV = B.IDMOV
    LEFT JOIN RATEIO C ON B.IDMOV = C.IDMOV AND B.NSEQITMMOV = C.NSEQITMMOV
    LEFT JOIN TPRD D ON B.IDPRD = D.IDPRD
    LEFT JOIN FORNCEDOR E ON A.CODCFO = E.CODCFO
    LEFT JOIN CC F ON C.CODCCUSTO = F.CODCCUSTO
    LEFT JOIN CorporeRM.GDEPTO G ON A.CODLOC COLLATE Latin1_General_CI_AS = G.CODDEPARTAMENTO AND A.CODFILIAL = G.CODFILIAL
)
SELECT * FROM UNIAO WHERE valor <> 0;
