USE HUBDADOS;

SELECT DISTINCT A.IDCNT AS 'ID CONTRATO', A.CODIGOCONTRATO AS 'CODIGO CONTRATO', B.IDPRD AS 'ID PRODUTO', FORMAT(B.PRECOFATURAMENTO, 'C', 'PT-BR') AS 'PREÇO FATURAMENTO', FORMAT(A.VALORCONTRATO, 'C', 'PT-BR') AS 'VALOR TOTAL CONTRATO' FROM CorporeRM.TCNT A
INNER JOIN CorporeRM.TITMCNT B
ON A.IDCNT = B.IDCNT
LEFT JOIN CorporeRM.TITMCNTADITIVO C
ON A.IDCNT = C.IDCNT
WHERE A.CODIGOCONTRATO LIKE '%VTG0.000484.25%'
ORDER BY IDPRD ASC

SELECT B.IDMOV AS 'ID MOVIMENTO', B.NUMEROMOV AS 'NÚMERO DO RECIBO', C.NOME AS 'RAZÃO SOCIAL', A.IDPRD AS 'ID PRODUTO', D.NOMEFANTASIA AS 'PRODUTO', FORMAT(A.PRECOUNITARIO, 'C', 'PT-BR') AS 'VALOR UNITÁRIO', FORMAT(A.QUANTIDADE, '#,0', 'PT-BR') AS 'QUANTIDADE', FORMAT(SUM(A.PRECOUNITARIO * A.QUANTIDADE), 'C', 'PT-BR') AS 'VALOR TOTAL', B.DATAEMISSAO AS 'DATA EMISSÃO' FROM CorporeRM.TITMMOV A
INNER JOIN CorporeRM.TMOV B
ON A.IDMOV = B.IDMOV
INNER JOIN CORPORERM.FCFO C
ON B.CODCFO = C.CODCFO
INNER JOIN CorporeRM.TPRD D
ON A.IDPRD = D.IDPRD
WHERE B.IDMOV = '5201588'
GROUP BY GROUPING SETS((B.IDMOV, A.IDPRD, D.NOMEFANTASIA, A.PRECOUNITARIO, A.QUANTIDADE, B.DATAEMISSAO), (B.IDMOV)), B.NUMEROMOV, C.NOME, C.NOMEFANTASIA
ORDER BY CASE WHEN A.IDPRD IS NULL THEN 1 ELSE 0 END, A.IDPRD ASC

SELECT DISTINCT CODTMV, CODUSUARIO, IDMOV, DATACRIACAO, A.CODFILIAL FROM CorporeRM.TMOV A
LEFT JOIN CorporeRM.GDEPTO B
ON A.CODDEPARTAMENTO = B.CODDEPARTAMENTO COLLATE SQL_Latin1_General_CP1_CI_AI AND A.CODFILIAL = B.CODFILIAL 
WHERE CODTMV = '2.2.14' AND YEAR(DATAEMISSAO) = '2025' AND STATUS <> 'C'
ORDER BY DATACRIACAO DESC